import type { IssueDocContext, RenderedPage } from './types.js';

const DOC_TYPE_LABEL: Record<IssueDocContext['docType'], string> = {
  handoff: 'Handoff',
  summary: 'Summary',
  escalation: 'Escalation Brief',
};

/**
 * Renders an IssueDocContext into a Confluence storage format page.
 * All output is deterministic and fully traceable — no LLM prose.
 *
 * Confluence storage format is an XHTML subset. Tags like <p>, <h2>, <ul>,
 * <li>, <ac:structured-macro> are valid. We use a minimal subset here.
 */
export function renderConfluencePage(ctx: IssueDocContext): RenderedPage {
  const label = DOC_TYPE_LABEL[ctx.docType];
  const title = `${ctx.issue.key} — ${label}`;

  const sections: string[] = [];

  // ── Issue header ────────────────────────────────────────────────────────
  sections.push(section(
    ctx.issue.title,
    table([
      ['Issue', `<a href="#">${ctx.issue.key}</a>`],
      ['Status', ctx.issue.status],
      ...(ctx.issue.assignee ? [['Assignee', ctx.issue.assignee] as [string, string]] : []),
      ...(ctx.issue.priority ? [['Priority', ctx.issue.priority] as [string, string]] : []),
      ...(ctx.department ? [['Department', ctx.department] as [string, string]] : []),
    ]),
  ));

  // ── Uploaded context (project brief) ────────────────────────────────────
  if (ctx.uploadedContext) {
    const age = Math.floor(
      (ctx.generatedAt.getTime() - ctx.uploadedContext.uploadedAt.getTime()) / (1000 * 60 * 60 * 24),
    );
    const ageWarning = age > 30
      ? `<p><em>⚠ This document is ${age} days old — verify it reflects the current state.</em></p>`
      : '';
    sections.push(section(
      'Project Brief',
      `${ageWarning}<p><strong>${esc(ctx.uploadedContext.filename)}</strong> (uploaded ${fmt(ctx.uploadedContext.uploadedAt)})</p>` +
      `<blockquote><p>${esc(ctx.uploadedContext.excerpt)}</p></blockquote>`,
    ));
  }

  // ── Timeline ────────────────────────────────────────────────────────────
  if (ctx.timeline.length > 0) {
    sections.push(section(
      'Timeline',
      table(ctx.timeline.map((e) => [
        fmt(e.date),
        esc(e.event) + (e.actor ? ` <em>(${esc(e.actor)})</em>` : ''),
      ])),
    ));
  }

  // ── Key Decisions ────────────────────────────────────────────────────────
  if (ctx.keyDecisions.length > 0) {
    sections.push(section(
      'Key Decisions',
      list(ctx.keyDecisions.map(
        (d) => `${esc(d.content)} <em>(via ${esc(d.source)}, ${fmt(d.citedAt)})</em>`,
      )),
    ));
  }

  // ── Blockers ─────────────────────────────────────────────────────────────
  if (ctx.blockers.length > 0) {
    sections.push(section(
      'Blockers',
      list(ctx.blockers.map(
        (b) => `${esc(b.content)} <em>(via ${esc(b.source)}, ${fmt(b.citedAt)})</em>`,
      )),
    ));
  }

  // ── Open Questions ────────────────────────────────────────────────────────
  if (ctx.openQuestions.length > 0) {
    sections.push(section(
      'Open Questions',
      list(ctx.openQuestions.map(
        (q) => `${esc(q.content)} <em>(via ${esc(q.source)}, ${fmt(q.citedAt)})</em>`,
      )),
    ));
  }

  // ── Participants ──────────────────────────────────────────────────────────
  if (ctx.participants.length > 0) {
    sections.push(section(
      'Participants',
      `<p>${ctx.participants.map(esc).join(', ')}</p>`,
    ));
  }

  // ── Linked Slack Threads ──────────────────────────────────────────────────
  if (ctx.linkedThreads.length > 0) {
    sections.push(section(
      'Linked Slack Threads',
      list(ctx.linkedThreads.map((t) => {
        const label = t.channelName ? `#${esc(t.channelName)}` : 'Slack thread';
        const link = t.permalink ? `<a href="${esc(t.permalink)}">${label}</a>` : label;
        return `${link} — ${t.messageCount} message${t.messageCount === 1 ? '' : 's'}`;
      })),
    ));
  }

  // ── Related Emails ────────────────────────────────────────────────────────
  if (ctx.relatedEmails.length > 0) {
    sections.push(section(
      'Related Emails',
      list(ctx.relatedEmails.map(
        (e) => `<em>${esc(e.subject)}</em> — ${e.participants.map(esc).join(', ')}`,
      )),
    ));
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  sections.push(
    `<p><em>Generated by Remi on ${fmt(ctx.generatedAt)}. ` +
    `All content is sourced from Slack threads, Jira events, and linked emails — ` +
    `verify before sharing externally.</em></p>`,
  );

  return { title, body: sections.join('\n') };
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function section(heading: string, content: string): string {
  return `<h2>${esc(heading)}</h2>\n${content}`;
}

function list(items: string[]): string {
  return `<ul>${items.map((i) => `<li><p>${i}</p></li>`).join('')}</ul>`;
}

function table(rows: [string, string][]): string {
  const cells = rows.map(
    ([k, v]) => `<tr><th><p>${esc(k)}</p></th><td><p>${v}</p></td></tr>`,
  );
  return `<table><tbody>${cells.join('')}</tbody></table>`;
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function fmt(d: Date): string {
  return d.toISOString().slice(0, 10); // YYYY-MM-DD
}
