import type { PrismaClient } from '@prisma/client';
import { getLatestSnapshot, createProposal, getMemoryUnit } from '@remi/db';
import type { MemoryModelClient } from '../clients/interface.js';
import { MODELS, PROMPT_VERSIONS, MIN_PROPOSAL_CONFIDENCE } from '../models.js';

export interface ProposalResult {
  commentBody: string;
  confidence: number;
}

export function buildProposalPrompt(): string {
  return `You are a documentation assistant for a workplace operations tool called Remi.

Given a memory snapshot for a Jira issue, generate a Jira comment summarising the current state. This comment will be proposed to a human for approval before posting.

Return JSON with:
- commentBody: the full Jira comment in Jira wiki markup (* for bold, # for headers, - for bullets)
- confidence: float 0.0–1.0

The comment must:
- Start with "📋 *Remi Memory Update*" as the heading
- Include current state, key decisions (if any), open actions (if any), blockers (if any)
- Be concise (max 300 words)
- Use past tense for decisions, present tense for current state
- Not claim certainty about low-confidence items
- End with: "_(Generated by Remi on {date})_"

Return only valid JSON. No markdown wrapping around the JSON.`;
}

export function parseProposalResponse(raw: string): ProposalResult {
  const parsed = JSON.parse(raw) as Partial<ProposalResult>;
  return {
    commentBody: parsed.commentBody ?? '',
    confidence: typeof parsed.confidence === 'number' ? parsed.confidence : 0,
  };
}

export async function runStage3(
  prisma: PrismaClient,
  memoryUnitId: string,
  snapshotId: string,
  client: MemoryModelClient,
): Promise<{ proposed: boolean; proposalId?: string }> {
  const snapshot = await getLatestSnapshot(prisma, memoryUnitId);
  if (!snapshot || snapshot.id !== snapshotId) return { proposed: false };

  const unit = await getMemoryUnit(prisma, memoryUnitId);
  if (!unit?.issue?.jiraIssueKey) return { proposed: false };

  const systemPrompt = buildProposalPrompt();
  const userContent = JSON.stringify({
    jiraIssueKey: unit.issue.jiraIssueKey,
    snapshot: {
      headline: snapshot.headline,
      currentState: snapshot.currentState,
      keyDecisions: snapshot.keyDecisions,
      openActions: snapshot.openActions,
      blockers: snapshot.blockers,
      openQuestions: snapshot.openQuestions,
    },
    generatedAt: new Date().toISOString(),
  });

  const raw = await client.complete(systemPrompt, userContent);
  const result = parseProposalResponse(raw);

  if (result.confidence < MIN_PROPOSAL_CONFIDENCE) return { proposed: false };

  const proposal = await createProposal(prisma, {
    memoryUnitId,
    snapshotId,
    payload: { jiraIssueKey: unit.issue.jiraIssueKey, commentBody: result.commentBody },
    citationIds: snapshot.sourceObsIds,
    confidence: result.confidence,
    modelId: MODELS.STAGE3_PROPOSE,
    promptVersion: PROMPT_VERSIONS.STAGE3_PROPOSE,
  });

  return { proposed: true, proposalId: proposal.id };
}
