import type { PrismaClient } from '@prisma/client';
import { getLatestSnapshot, createProposal, getMemoryUnit } from '@remi/db';
import type { MemoryModelClient } from '../clients/interface.js';
import { MODELS, PROMPT_VERSIONS, MIN_PROPOSAL_CONFIDENCE } from '../models.js';

export interface ProposalResult {
  commentBody: string;
  confidence: number;
}

export function buildProposalPrompt(): string {
  return `You are the Stage 3 writeback proposal generator for Remi.

Given a memory snapshot for a Jira issue, generate a concise Jira comment for human review before posting. The snapshot may aggregate data from multiple workplace tools (Slack, email, Jira, etc.) — the dataSources field lists which tools contributed.

Important: output plain text only. Do not use markdown syntax, wiki markup, tables, or emojis. Write a clean professional update that can be pasted directly into Jira as plain text.

Return valid JSON with:
{
  "commentBody": string,
  "confidence": number
}

Goal:
Produce a clear operational update that helps a Jira reader understand the current issue state without needing to check Slack, email, or Jira history separately.

Comment requirements:
- Start with "Remi Memory Update"
- Use short plain-text labels and simple dash bullets
- Maximum 220 words
- Include only sections that contain meaningful information
- Prefer operational clarity over completeness
- Use past tense for decisions
- Use present tense for current state and blockers
- Use imperative or neutral task language for open actions
- If snapshot confidence is moderate or low, or freshness is not recent, use cautious wording such as "appears", "currently indicates", or "based on recent activity"
- Do not mention internal fields like confidence, citations, snapshot IDs, or model details
- Do not sound promotional or AI-generated
- End with an attribution line: if dataSources has more than one entry, write "Sources: {comma-separated capitalized app names}  ·  Generated by Remi on {generatedAt}". If only one source, write "Generated by Remi on {generatedAt}".

Preferred section order:
1. Current state
2. Owners, if meaningful
3. Key decisions, if any
4. Open actions, if any
5. Blockers, if any
6. Open questions, if any

Writing rules:
- Use only the information in the provided snapshot
- Do not invent evidence, owners, dates, certainty, or resolution
- Do not claim something is resolved unless the snapshot clearly supports it
- Omit empty sections entirely
- Prefer 1 to 3 bullets per section
- Keep each bullet concrete and action-oriented
- If there is not enough information for a useful Jira update, keep the comment minimal and set confidence below the threshold

Return only valid JSON. No markdown wrapper. No explanation.`;
}

export function parseProposalResponse(raw: string): ProposalResult {
  const parsed = JSON.parse(raw) as Partial<ProposalResult>;
  return {
    commentBody: typeof parsed.commentBody === 'string' ? parsed.commentBody.trim() : '',
    confidence:
      typeof parsed.confidence === 'number'
        ? Math.max(0, Math.min(1, parsed.confidence))
        : 0,
  };
}

export async function runStage3(
  prisma: PrismaClient,
  memoryUnitId: string,
  snapshotId: string,
  client: MemoryModelClient,
): Promise<{ proposed: boolean; proposalId?: string }> {
  const snapshot = await getLatestSnapshot(prisma, memoryUnitId);
  if (!snapshot || snapshot.id !== snapshotId) return { proposed: false };

  const unit = await getMemoryUnit(prisma, memoryUnitId);
  if (!unit?.issue?.jiraIssueKey) return { proposed: false };

  const systemPrompt = buildProposalPrompt();
  const userContent = JSON.stringify({
    jiraIssueKey: unit.issue.jiraIssueKey,
    snapshot: {
      headline: snapshot.headline,
      currentState: snapshot.currentState,
      keyDecisions: snapshot.keyDecisions,
      openActions: snapshot.openActions,
      blockers: snapshot.blockers,
      openQuestions: snapshot.openQuestions,
      owners: snapshot.owners,
      dataSources: snapshot.dataSources ?? [],
      confidence: snapshot.confidence,
      freshness: snapshot.freshness.toISOString(),
    },
    generatedAt: new Date().toISOString(),
  });

  const raw = await client.complete(systemPrompt, userContent);
  const result = parseProposalResponse(raw);
  const proposalConfidence = Math.min(result.confidence, snapshot.confidence);

  if (!result.commentBody) return { proposed: false };
  if (proposalConfidence < MIN_PROPOSAL_CONFIDENCE) return { proposed: false };

  const proposal = await createProposal(prisma, {
    memoryUnitId,
    snapshotId,
    payload: { jiraIssueKey: unit.issue.jiraIssueKey, commentBody: result.commentBody },
    citationIds: snapshot.sourceObsIds,
    confidence: proposalConfidence,
    modelId: MODELS.STAGE3_PROPOSE,
    promptVersion: PROMPT_VERSIONS.STAGE3_PROPOSE,
  });

  return { proposed: true, proposalId: proposal.id };
}
